### ISSUE TITLE
Next steps

### ISSUE THREAD

**Issue by ineiti** [c4dt/predictive-maintenance#3]
Here some jumbled possible next steps - to be cleaned up as we go along:

- create our own testing data using StableDiffusion (mostly if we see we don't have enough with the MVTech data)
- implement the slicing of the ResNet intermediary layer: instead of having the whole layer inputted to the MLP, do a
sliced implementation like in PatchCore and PNI, so that we can know where the error is

**Comment by lanterno** [comment]
We should close this ticket.
